POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QgVXNlcjMiLCJpZCI6IjViOTdkM2VjMDc2NDkyMmZjYzZjNWUyMCIsImlhdCI6MTUzNjczNzUwMn0.1EoUxKafoFlyH4aYbrtA2wTR45Tb-ABoyKBaOJYSK2A

{
  "title": "Test post with auth3",
  "author": "Erkki",
  "url": "www.microsoftAUTH3.com",
  "likes": 300
}
